version: '3.8'

services:
  agent:
    build: .
    container_name: agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_JID: "alpha-pi-zero-agent@prosody"
      XMPP_PASSWORD: "top_secret"
    volumes:
      - ./agent:/agent
